"""Add remaining plans columns and goals table

Revision ID: 28da3b77e782
Revises: 927b8528f6fb
Create Date: 2022-01-10 13:26:54.770584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28da3b77e782'
down_revision = '927b8528f6fb'
branch_labels = None
depends_on = None


def upgrade():

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('goal_name', sa.String(), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('goal_description', sa.String(), nullable=False),
    sa.Column('goal_period', sa.Integer(), nullable=False),
    sa.Column('goal_created_by', sa.Integer(), nullable=False),
    sa.Column('goal_created_date', sa.Date(), nullable=False),
    sa.Column('goal_last_modified_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('goal_last_modified_by', sa.Integer(), nullable=False),
    sa.Column('goal_deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('goal_id')
    )
    op.add_column('plans', sa.Column('plan_id', sa.Integer(), autoincrement=True, nullable=False, primary_key=True))
    op.add_column('plans', sa.Column('plan_end_date', sa.Date(), nullable=False))
    op.add_column('plans', sa.Column('plan_status', sa.Integer(), nullable=False))
    op.add_column('plans', sa.Column('plan_created_by', sa.Integer(), nullable=False))
    op.add_column('plans', sa.Column('plan_created_date', sa.Date(), nullable=False))
    op.add_column('plans', sa.Column('plan_last_modified_by', sa.Integer(), nullable=False))
    op.add_column('plans', sa.Column('plan_last_modified_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('plans', sa.Column('plan_deleted_at', sa.DateTime(), nullable=True))
    op.drop_column('plans', 'id')
    op.add_column('users', sa.Column('user_created_by', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('user_created_date', sa.Date(), nullable=False))
    op.add_column('users', sa.Column('user_last_modified_by', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('user_deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_deleted_at')
    op.drop_column('users', 'user_last_modified_by')
    op.drop_column('users', 'user_created_date')
    op.drop_column('users', 'user_created_by')
    op.add_column('plans', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('plans', 'plan_deleted_at')
    op.drop_column('plans', 'plan_last_modified_date')
    op.drop_column('plans', 'plan_last_modified_by')
    op.drop_column('plans', 'plan_created_date')
    op.drop_column('plans', 'plan_created_by')
    op.drop_column('plans', 'plan_status')
    op.drop_column('plans', 'plan_end_date')
    op.drop_column('plans', 'plan_id')
    op.drop_table('goals')
    # ### end Alembic commands ###
