"""add a phone number to users table

Revision ID: 7f4a5c0188f4
Revises: 8ef76d83b1eb
Create Date: 2022-01-10 13:59:12.590840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f4a5c0188f4'
down_revision = '8ef76d83b1eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_phone_number')
    # ### end Alembic commands ###
