"""Add a plans to goal foreign keys

Revision ID: d03a2081ed20
Revises: 28da3b77e782
Create Date: 2022-01-10 13:38:39.487923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd03a2081ed20'
down_revision = '28da3b77e782'
branch_labels = None
depends_on = None


def upgrade():
    op.create_primary_key("plan_primary_key","plans",["plan_id"])
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key("fk_goals_plan_id", 'goals', 'plans', ['plan_id'], ['plan_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_goals_plan_id", 'goals', type_='foreignkey')
    # ### end Alembic commands ###
    op.drop_constraint("plan_primary_key","plans")
